spring.application.name=currency-converter-api

java.runtime.version=17

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
server.port=8081

spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:currency_db}
spring.datasource.url=jdbc:mysql://afglv9z9hspzbjt6:qxm1wm9payo05xo4@a5s42n4idx9husyc.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/u74bwrzb646zkpcp/${DATABASE_NAME:currency_db}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD:admin}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# Application specific properties

config.api.providers[0].name=Exchange Rates Api
config.api.providers[0].key=EXCHANGE_RATES_API_PROVIDER
config.api.providers[0].url=https://api.exchangeratesapi.io/v1/latest
config.api.providers[0].apiKey=212c807c558aaa2a2dba5a98696d08e5

config.api.providers[1].name=Sandbox Api
config.api.providers[1].key=SANDBOX_PROVIDER
config.api.providers[1].url=https://google.com
config.api.providers[1].apiKey=123456