spring.application.name=currency-converter-api

spring.profiles.active=dev

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# Application specific properties

config.api.providers[0].name=Exchange Rates Api
config.api.providers[0].key=EXCHANGE_RATES_API_PROVIDER
config.api.providers[0].url=https://api.exchangeratesapi.io/v1/latest
config.api.providers[0].apiKey=212c807c558aaa2a2dba5a98696d08e5

config.api.providers[1].name=Sandbox Api
config.api.providers[1].key=SANDBOX_PROVIDER
config.api.providers[1].url=https://google.com
config.api.providers[1].apiKey=123456